import type { TestVariable } from '../variables';

/**
 * The environment file a generated script needs in order to run.
 *
 * Non-secret values are filled in — the user defined them, and a test phone
 * number is what makes the file immediately usable. **Secret values are left
 * blank on purpose.** Writing a password into a downloaded file turns a
 * deliberate act into an accident waiting for someone to `git add .`, and the
 * blank line with a comment above it is a better prompt than a filled one.
 */

export interface EnvFile {
  filename: string;
  content: string;
  /** Names the user still has to fill in by hand. */
  blanks: string[];
}

/**
 * dotenv strips a wrapping pair of quotes, so a value only needs them when it
 * contains something that would otherwise end the line or start a comment.
 */
function envValue(value: string): string {
  if (!value) return '';
  if (/[\s#"'\\]/.test(value)) {
    return `"${value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
  }
  return value;
}

function resolve(names: string[], variables: TestVariable[]) {
  return names.map((name) => {
    const defined = variables.find((entry) => entry.name === name);
    return {
      name,
      // A secret is known to the extension but deliberately not written out.
      value: defined && !defined.secret ? defined.value : '',
      secret: defined?.secret ?? true,
      known: defined != null,
    };
  });
}

export function toEnvFile(
  names: string[],
  variables: TestVariable[],
  testTitle: string,
): EnvFile {
  const rows = resolve(names, variables);

  const lines = [
    `# Test data for "${testTitle}"`,
    '# Generated by QA Test Case Recorder.',
    '#',
    '# Add this file to .gitignore. It is meant to hold credentials and must not',
    '# be committed.',
    '',
  ];

  for (const row of rows) {
    if (row.secret) {
      lines.push(
        row.known
          ? `# ${row.name} is marked secret, so its value is not written here.`
          : `# ${row.name} is not defined under Tools -> Test data.`,
        `${row.name}=`,
      );
    } else {
      lines.push(`${row.name}=${envValue(row.value)}`);
    }
    lines.push('');
  }

  return {
    filename: '.env',
    content: lines.join('\n'),
    blanks: rows.filter((row) => row.secret).map((row) => row.name),
  };
}

export function toCypressEnvFile(
  names: string[],
  variables: TestVariable[],
): EnvFile {
  const rows = resolve(names, variables);

  // JSON has no comments, so the guidance for this one lives in the panel and
  // the README rather than in the file.
  const object = Object.fromEntries(rows.map((row) => [row.name, row.value]));

  return {
    filename: 'cypress.env.json',
    content: `${JSON.stringify(object, null, 2)}\n`,
    blanks: rows.filter((row) => row.secret).map((row) => row.name),
  };
}
